server:
  port: 8080
  servlet:
    context-path: /shopapp
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

upload:
  path: uploads

jwt:
  signer-key: "rE9QgarzE1K18TwxJfY8XwkQsF0B50trW7wbVCe+0rwzsO1/Phcij2y/cY3sFGEV"
  valid-duration: 3600
  refreshable-duration: 36000
