server:
  port: 8080
  servlet:
    context-path: /shopapp
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/shopapp}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

upload:
  path: uploads

jwt:
  signer-key: "0ghcd9Ns7haKp9aqF4Vtftpf/8h3bP18ttqbr2z9UfPAwSEJIOZnT3nRVMgUdsNp"
  valid-duration: 3600
  refreshable-duration: 36000
